# Copyright 2026 The TensorFlow MUSA Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Manifest of custom MUSA TensorFlow ops exposed to Python."""

CUSTOM_OPS = [{'op': 'MusaBatchMatMulV2',
  'raw': 'musa_batch_mat_mul_v2',
  'api': 'batch_mat_mul_v2',
  'source': 'musa_ext/kernels/math/musa_matmul_op.cc'},
 {'op': 'MusaBiasAddReluMatMul',
  'raw': 'musa_bias_add_relu_mat_mul',
  'api': 'bias_add_relu_mat_mul',
  'source': 'musa_ext/kernels/fusion/musa_rgprojection_fusion_op.cc'},
 {'op': 'MusaClip',
  'raw': 'musa_clip',
  'api': 'clip',
  'source': 'musa_ext/kernels/fusion/musa_clip_op.cc'},
 {'op': 'MusaConcatMatMul',
  'raw': 'musa_concat_mat_mul',
  'api': 'concat_mat_mul',
  'source': 'musa_ext/kernels/fusion/musa_concat_matmul_op.cc'},
 {'op': 'MusaDropout',
  'raw': 'musa_dropout',
  'api': 'dropout',
  'source': 'musa_ext/kernels/nn/musa_dropout_op.cc'},
 {'op': 'MusaDropoutGrad',
  'raw': 'musa_dropout_grad',
  'api': 'dropout_grad',
  'source': 'musa_ext/kernels/nn/musa_dropout_op.cc'},
 {'op': 'MusaGelu',
  'raw': 'musa_gelu',
  'api': 'gelu',
  'source': 'musa_ext/kernels/fusion/musa_gelu_op.cc'},
 {'op': 'MusaInteract',
  'raw': 'musa_interact',
  'api': 'interact',
  'source': 'musa_ext/kernels/array/musa_tensorinteraction_op.cc'},
 {'op': 'MusaLayerNorm',
  'raw': 'musa_layer_norm',
  'api': 'layer_norm',
  'source': 'musa_ext/kernels/fusion/musa_layernorm_op.cc'},
 {'op': 'MusaLinearActivation',
  'raw': 'musa_linear_activation',
  'api': 'linear_activation',
  'source': 'musa_ext/kernels/fusion/musa_linear_relu_op.cc'},
 {'op': 'MusaMatMul',
  'raw': 'musa_mat_mul',
  'api': 'mat_mul',
  'source': 'musa_ext/kernels/math/musa_matmul_op.cc'},
 {'op': 'MusaMatMulBiasAdd',
  'raw': 'musa_mat_mul_bias_add',
  'api': 'matmul_bias_add',
  'source': 'musa_ext/kernels/fusion/musa_matmul_bias_op.cc'},
 {'op': 'MusaMaximum',
  'raw': 'musa_maximum',
  'api': 'maximum',
  'source': 'musa_ext/kernels/math/musa_maximum_op.cc'},
 {'op': 'MusaMean',
  'raw': 'musa_mean',
  'api': 'mean',
  'source': 'musa_ext/kernels/math/musa_mean_op.cc'},
 {'op': 'MusaNormalize',
  'raw': 'musa_normalize',
  'api': 'normalize',
  'source': 'musa_ext/kernels/fusion/musa_normalize_fusion_op.cc'},
 {'op': 'MusaPlnCascade',
  'raw': 'musa_pln_cascade',
  'api': 'pln_cascade',
  'source': 'musa_ext/kernels/fusion/musa_pln_cascade_op.cc'},
 {'op': 'MusaPlnCascadeBlock',
  'raw': 'musa_pln_cascade_block',
  'api': 'pln_cascade_block',
  'source': 'musa_ext/kernels/fusion/musa_pln_cascade_block_op.cc'},
 {'op': 'MusaPRelu',
  'raw': 'musa_p_relu',
  'api': 'prelu',
  'source': 'musa_ext/kernels/fusion/musa_prelu_fusion_op.cc'},
 {'op': 'MusaReshapeMatMul',
  'raw': 'musa_reshape_mat_mul',
  'api': 'reshape_mat_mul',
  'source': 'musa_ext/kernels/fusion/musa_reshape_matmul_op.cc'},
 {'op': 'MusaResourceApplyAdamMixed',
  'raw': 'musa_resource_apply_adam_mixed',
  'api': 'resource_apply_adam_mixed',
  'source': 'musa_ext/kernels/training/musa_applyadam_mixed_op.cc'},
 {'op': 'MusaResourceSparseApplyAdam',
  'raw': 'musa_resource_sparse_apply_adam',
  'api': 'resource_sparse_apply_adam',
  'source': 'musa_ext/kernels/training/musa_apply_sparse_adam_op.cc'},
 {'op': 'MusaShiftedAffineMap',
  'raw': 'musa_shifted_affine_map',
  'api': 'shifted_affine_map',
  'source': 'musa_ext/kernels/fusion/musa_shifted_affine_map_op.cc'},
 {'op': 'MusaTensorDot',
  'raw': 'musa_tensor_dot',
  'api': 'tensor_dot',
  'source': 'musa_ext/kernels/fusion/musa_tensordot_op.cc'},
 {'op': 'MusaTensorDotBias',
  'raw': 'musa_tensor_dot_bias',
  'api': 'tensor_dot_bias',
  'source': 'musa_ext/kernels/fusion/musa_tensordot_bias_op.cc'},
 {'op': 'MusaTokenMixer',
  'raw': 'musa_token_mixer',
  'api': 'token_mixer',
  'source': 'musa_ext/kernels/fusion/musa_tokenmixer_op.cc'},
 {'op': 'ResourceApplyNadam',
  'raw': 'ResourceApplyNadam',
  'api': 'resource_apply_nadam',
  'source': 'musa_ext/kernels/training/musa_resource_apply_nadam_op.cc'}]

CUSTOM_OP_NAMES = tuple(entry["op"] for entry in CUSTOM_OPS)
RAW_OP_NAMES = tuple(entry["raw"] for entry in CUSTOM_OPS)
PUBLIC_API_NAMES = tuple(entry["api"] for entry in CUSTOM_OPS)
